version: "3.7"

services:
  server:
    build:
      context: .
    env_file:
      - .env
    environment:
      - PORT=8000
    ports:
      - "${APP_PORT:-8080}:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - exchange-register-default

networks:
  exchange-register-default:
    driver: bridge
